version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:${PATH_ROOT}
    ports:
      - '8000:80'
    networks:
      - app
    depends_on:
      - php

  php:
    build: ./docker
    working_dir: ${PATH_ROOT}
    volumes:
      - ./src:${PATH_ROOT}
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - app
    depends_on:
      - mysql

  node:
    image: node:latest
    working_dir: ${PATH_ROOT}
    volumes:
      - ./src:${PATH_ROOT}
    entrypoint: tail -f /dev/null
    networks:
      - app
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "8002:3306"
    networks:
      - app

  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data
    ports:
      - "8003:6379"
    networks:
      - app

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '8025:1025'
      - '8026:8025'
    networks:
      - app

networks:
  app:
    driver: bridge