version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:${PATH_ROOT}
    ports:
      - '80:80'
    expose:
      - 80
      - 5173
    networks:
      - app
    depends_on:
      - php

  php:
    build: ./docker
    working_dir: ${PATH_ROOT}
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:${PATH_ROOT}
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    ports:
      - '3000:3000'
    environment:
      - HOST=0.0.0.0
      - PORT=5173
    networks:
      - app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "8006:3306"
    networks:
      - app

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app

networks:
  app:
    driver: bridge