version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/application
    ports:
      - '8000:80'
    networks:
      - app
    depends_on:
      - php

  php:
    build:
      context: docker
      dockerfile: php.Dockerfile
    container_name: app
    working_dir: /application
    volumes:
      - ./src:/application
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "8002:3306"
    networks:
      - app

  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data
    ports:
      - "8003:6379"
    networks:
      - app

networks:
  app:
    driver: bridge